sets.exported={
    main="Daybreak",
    sub="Genmei Shield",
    ammo="Esper Stone +1",
    head={ name="Peda. M.Board +1", augments={'Enh. "Altruism" and "Focalization"',}},
    body={ name="Gende. Bilaut +1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -2%','Song spellcasting time -4%',}},
    hands={ name="Gende. Gages +1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -4%','Song spellcasting time -3%',}},
    legs="Assid. Pants +1",
    feet={ name="Gende. Galosh. +1", augments={'Phys. dmg. taken -3%','Magic dmg. taken -4%','"Cure" potency +2%',}},
    neck="Loricate Torque +1",
    waist="Luminary Sash",
    left_ear="Eabani Earring",
    right_ear="Etiolation Earring",
    left_ring="Defending Ring",
    right_ring="Lebeche Ring",
    back="Aurist's Cape +1",
}